on:
  - pull_request
  - push

name: CI

jobs:
  tests:
    name: Tests

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest

        php:
          - "5.3"
          - "5.4"
          - "5.5"
          - "5.6"
          - "7.0"
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, zip
          ini-values: assert.exception=1, zend.assertions=1

      - name: Install composer dependencies ignoring platform requirements
        if: matrix.php == '8.0'
        run: composer install --no-ansi --no-interaction --no-progress --ignore-platform-reqs

      - name: Install composer dependencies
        if: matrix.php != '8.0'
        run: composer update --no-ansi --no-interaction --no-progress

      - name: Run tests with phpunit
        run: vendor/bin/phpunit --coverage-clover=coverage.xml
